#!/bin/bash

BASE_DIR="$CHEATSHEET_PATH"

if [ ! -d "$BASE_DIR" ]; then
    echo "Error: $BASE_DIR does not exist."
fi

# argument check
if [ -z "$1" ]; then
    echo "Usage: cs <topic>"
    echo "--- Available sheets ---"
    ls "$BASE_DIR" | grep '\.md$' | sed 's/\.md$//' | column
    exit 1
fi

# match file with argument
# -maxdepth 1: Only looks in the base folder 
FILE=$(find -L "$BASE_DIR" -maxdepth 1 -iname "$1.md" -type f | head -n 1)

if [ -n "$FILE" ]; then
    less -R "$FILE"
else
    echo "No cheatsheet found for '$1' in $BASE_DIR"
    echo "--- Available sheets ---"
    ls "$BASE_DIR" | grep '\.md$' | sed 's/\.md$//' | column
fi
